# Generated by Django 3.2.2 on 2021-05-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Employeename', models.CharField(max_length=40)),
                ('Department', models.CharField(max_length=20)),
                ('Email', models.EmailField(default='', max_length=20, unique=True)),
                ('Dateofbirth', models.DateField(blank=True, null=True)),
                ('Picture', models.ImageField(blank=True, default='0', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Departmentname', models.CharField(max_length=20)),
                ('Manager', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
